### ISSUE TITLE
Create a Issue and Pull Request template for the new contributors

### ISSUE THREAD

**Issue by CS50X-RGB** [CS50X-RGB/File-Uploader#11]
Create a issue and pull request template for the new contributors to contribute so if anyone wants to contribute they will use those templates

**Comment by mhamzanadeem** [comment]
@CS50X-RGB Can you explain it briefly ? Which templates are you talking about ? Are You talking about templates for issue ?

**Comment by CS50X-RGB** [comment]
@mhamzanadeem there should be md files or templates using which the contributor should create a new Issue which would consist of there issue heading issue description how will they solve this is it a bug or feature ans lastly during all the things mentioned above plus the images of how its working fine during the pull request.

**Comment by CS50X-RGB** [comment]
@mhamzanadeem  You can search on some github docs it would help

**Comment by mhamzanadeem** [comment]
@CS50X-RGB  can you assign me this issue ?  I will find templates and share with you

**Comment by CS50X-RGB** [comment]
@mhamzanadeem  dont share it add it to repo according to the needs and go ahead

**Comment by SuryaCreatX** [comment]
Can you assign me this issue?

**Comment by CS50X-RGB** [comment]
> Can you assign me this issue?
> 

Actually @mhamzanadeem is working on it
