### ISSUE TITLE
Add Contribution Docs

### ISSUE THREAD

**Issue by CS50X-RGB** [CS50X-RGB/File-Uploader#4]
Add Contribution Docs for the user

**Comment by mhamzanadeem** [comment]
@CS50X-RGB  can u assign me this issue ?

**Comment by CS50X-RGB** [comment]
Sure @mhamzanadeem  go ahead

**Comment by mhamzanadeem** [comment]
> Sure @mhamzanadeem  go ahead

@CS50X-RGB  Do you recommend any specific guideline to be included in contributing.md ?

**Comment by CS50X-RGB** [comment]
> > Sure @mhamzanadeem  go ahead
> 
> @CS50X-RGB  Do you recommend any specific guideline to be included in contributing.md ?

Yeah like if they're raising a issue they should provide detailed info about that with a heading of the problem how it can be solved. 
And if the issue is already created and anyone gets the issue assigned we will give them 3-6 days at max to solve the issue  depending on their issue type

**Comment by CS50X-RGB** [comment]
@mhamzanadeem I have got some changes I have to assign this issue to @Mannxxx because the work is done u can take issue #7

**Comment by CS50X-RGB** [comment]
@Mannxxx

**Comment by CS50X-RGB** [comment]
@Mannxxx message here so that I can assign you this task for which you have made the pull request

**Comment by Mannxxx** [comment]
Hey @CS50X-RGB, you can now assign me this task.
