### ISSUE TITLE
Update Contribution Docs

### ISSUE THREAD

**Issue by CS50X-RGB** [CS50X-RGB/File-Uploader#7]
Update the Contribution Docs to make it more developer friendly

**Comment by mhamzanadeem** [comment]
@CS50X-RGB  assign me this issue

**Comment by CS50X-RGB** [comment]
@mhamzanadeem assigned

**Comment by mhamzanadeem** [comment]
@CS50X-RGB my pull request is not accepted by hacktoberfest

![IMG_20231009_175402.jpg](https://github.com/CS50X-RGB/CLI-Bluetooth./assets/114602354/9f399cc9-fce5-4cc1-b092-13bdc427085f)
